version: '3.7'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: inventory:0.1
    ports:
      - "8001:8000"
    env_file:
      - .env
    container_name: django-container-inventory